// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainComponent.Infrastructure.Persistence;

#nullable disable

namespace TrainComponent.Migrations
{
    [DbContext(typeof(TrainDbContext))]
    [Migration("20250727081541_SeedComponents")]
    partial class SeedComponents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainComponent.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAssignQuantity")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UniqueNumber")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("TrainComponent.Domain.Entities.ComponentQuantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId")
                        .IsUnique();

                    b.ToTable("ComponentQuantities", t =>
                        {
                            t.HasCheckConstraint("CK_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("TrainComponent.Domain.Entities.ComponentQuantity", b =>
                {
                    b.HasOne("TrainComponent.Domain.Entities.Component", "Component")
                        .WithOne("Quantity")
                        .HasForeignKey("TrainComponent.Domain.Entities.ComponentQuantity", "ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("TrainComponent.Domain.Entities.Component", b =>
                {
                    b.Navigation("Quantity");
                });
#pragma warning restore 612, 618
        }
    }
}
